"""Add prefix to APIKey

Revision ID: cffcddd929b0
Revises: 7780beb3a99a
Create Date: 2026-09-18 22:45:20.885357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cffcddd929b0'
down_revision: Union[str, Sequence[str], None] = '7780beb3a99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('prefix', sa.String(), nullable=False))
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_column('api_keys', 'prefix')
    # ### end Alembic commands ###
